### ISSUE TITLE
Calendar items not synchronising

### ISSUE THREAD

**Issue by dnietzsche** [MShekow/outlook-calendar-sync#1]
Excellent tool MShekow, I've tested it today and works really well. Only a couple of issues that I wonder if you have experienced.

1. When I create Manual appointments in either calendars (e.g. an appointment without location or **invitees**, a doctor's appointment...)  the script does not pick those up
2. The SyncBlocker events are not inheriting the original categories such as free, tentative, busy, working elsewhere or out of office and they are all created as "busy"

Thanks

**Comment by MShekow** [comment]
Hey. 

1. Weird, I also have such kinds of appointments, and the script picks them up just fine. You should probably look at one of the executions of the flow, and check where these events go missing. For instance, are they at least present in the output of the _Get calendar view of events calX_ action?
2. Yes, this was done intentionally, although I cannot recall the reason anymore. I'm currently working on a new version where I use the same `showAs` value in the syncblocker events as in the original ones. I'll update the zip in this repo once everything works as expected.

**Comment by MShekow** [comment]
There is now a new v0.3 release that addresses the 2nd point.

**Comment by dnietzsche** [comment]
Great, thanks for preparing this new version. For point 1 found that it gets fixed if I add "none" to the "eventResponseTypes" array.

**Comment by MShekow** [comment]
OK. I'll close this ticket then.

> For point 1 found that it gets fixed if I add "none" to the "eventResponseTypes" array.

Sounds weird to me that this fixes the bug, because appointments you create for yourself have the eventResponseType = `organizer`.
