### ISSUE TITLE
How do I upgrade to a new version?

### ISSUE THREAD

**Issue by arcegabriel** [MShekow/outlook-calendar-sync#5]
I already installed a version last year and it is running. How do I upgrade to the latest version

**Comment by MShekow** [comment]
You disable your old flow ("Turn off" is the name of the button, I think), then you import the new version, edit it, tweak its settings so that they have the same setting values as your old (now disabled) flow, then save your changes to the new flow.

**Comment by arcegabriel** [comment]
Thanks
